
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path
import os
import pymysql.cursors
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Desktop\TKinter\Project\Login\assets delete\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def swap_to_add():
    window.destroy()
    os.system('python add.py')

def swap_to_dashboard():
    window.destroy()
    os.system('python dashboard.py')

def swap_to_login():
    window.destroy()
    os.system('python login.py')

def swap_to_search():
    window.destroy()
    os.system('python search.py')

def swap_to_updatestudent():
    window.destroy()
    os.system('python updatestudent.py')

window = Tk()

window.geometry("1450x780")
window.configure(bg="#FFFFFF")

canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=780,
    width=1450,
    bd=0,
    highlightthickness=0,
    relief="ridge"
)

canvas.place(x=0, y=0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    959.0,
    401.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    960.0,
    390.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFDFD",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=772.0,
    y=362.0,
    width=376.0,
    height=54.0
)

canvas.create_text(
    883.0,
    321.0,
    anchor="nw",
    text="Enter Student ID",
    fill="#000000",
    font=("Imprima Regular", 20 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    228.0,
    410.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    216.0,
    112.0,
    image=image_image_3
)

canvas.create_text(
    129.0,
    231.0,
    anchor="nw",
    text="Admin Username",
    fill="#FFFFFF",
    font=("Inika", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=swap_to_updatestudent,
    relief="flat", )

button_1.place(
    x=1.28369140625,
    y=535.62451171875,
    width=455.7162780761719,
    height=81.54146575927734
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=swap_to_login,
    relief="flat"
)
button_2.place(
    x=0.0,
    y=698.70751953125,
    width=455.7162780761719,
    height=81.54146575927734
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=0.0,
    y=617.166015625,
    width=455.7162780761719,
    height=81.54146575927734
)

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=swap_to_add,
    relief="flat"
)
button_4.place(
    x=0.0,
    y=454.0830078125,
    width=455.7162780761719,
    height=81.54146575927734
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=swap_to_search,
    relief="flat"
)
button_5.place(
    x=1.28369140625,
    y=372.54150390625,
    width=455.7162780761719,
    height=81.54146575927734
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=swap_to_dashboard,
    relief="flat"
)
button_6.place(
    x=1.28369140625,
    y=291.0,
    width=455.7162780761719,
    height=81.54146575927734
)


# STEP 1 - IMPORT PYMYSQL
# import pymysql.cursors

from tkinter import messagebox

def delete_student():
    import pymysql

    conn = None
    try:
        # STEP 2 - CONNECT WITH MYSQL DATABASE
        conn = pymysql.connect(host='127.0.0.1', user='root', password='104969', db='studentmanagement')
    except Exception as ex:
        print('PROBLEM WITH Database Connection', ex)
    else:
        print('Database Connection SUCCESS')

    query = "DELETE FROM students WHERE StudentID = %s"

    try:
        # STEP 6 - CREATE cursor Object
        cursor = conn.cursor()

        # STEP 7 - EXECUTE THE Query
        noofrecoredinsert = cursor.execute(query, (entry_1.get()))
    except Exception as e:
        print('DELETE PROBLEM ', e)
    else:
        if noofrecoredinsert > 0:
            # Show success message
            messagebox.showinfo('Delete Student', 'Student record deleted successfully.')
            # STEP 8 - Commit Database
            conn.commit()
        else:
            messagebox.showinfo('Delete Student', 'No student record found with the provided ID.')
    finally:
        if conn:
            conn.close()

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=delete_student,
    relief="flat"
)
button_7.place(
    x=878.0,
    y=475.0,
    width=163.1999969482422,
    height=49.0
)

canvas.create_text(
    855.0,
    200.0,
    anchor="nw",
    text="Delete Student",
    fill="#000000",
    font=("Imprima Regular", 32 * -1)
)
window.resizable(False, False)
window.mainloop()
