import os
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\Admin\Desktop\TKinter\Project\login\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1450x780")
window.configure(bg = "#FFFFFF")

def check_login():
    if entry_1.get() == "MUKHERJEE" and entry_2.get() == "COSCsummer2024":
        messagebox.showinfo('WELCOME BACK', "Good morning, afternoon, evening professor.")
        window.destroy()  # Close the login window
        os.system('python dashboard.py')  # Open the dashboard.py file
    else:
        messagebox.showerror('LOG IN FAIL', "Please try again.")

canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 780,
    width = 1450,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    739.0,
    512.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    747.0,
    386.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    805.0,
    422.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FAFCFD",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=659.0,
    y=394.0,
    width=292.0,
    height=55.0
)

canvas.create_text(
    649.0,
    303.0,
    anchor="nw",
    text="Admin Login",
    fill="#0C0C0C",
    font=("Mplus1p Bold", 32 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    805.0,
    521.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FAFCFD",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=659.0,
    y=493.0,
    width=292.0,
    height=55.0
)

canvas.create_text(
    491.0,
    508.0,
    anchor="nw",
    text="PASSWORD",
    fill="#000000",
    font=("MerriweatherSansRoman ExtraBold", 20 * -1)
)

canvas.create_text(
    491.0,
    411.0,
    anchor="nw",
    text="USERNAME",
    fill="#000000",
    font=("MerriweatherSansRoman ExtraBold", 20 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda:check_login(),
    relief="flat"
)
button_1.place(
    x=700.0,
    y=598.0,
    width=93.85003662109375,
    height=35.0
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    747.0,
    210.0,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    477.0,
    425.0,
    image=image_image_4
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    477.0,
    522.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    477.0,
    521.0,
    image=image_image_6
)
window.resizable(False, False)
window.mainloop()
